project:
  name: quickstart-salesforce-industries-virtual-calls
  owner: quickstart-eng@amazon.com
  template: templates/salesforce-industries-virtual-calls.template.yaml
  # parameters:
  # regions:
tests:
  defaults:
    regions:
      - us-east-1
