// Include any postdeployment steps here, such as steps necessary to test that the deployment was successful. If there are no postdeployment steps, leave this file empty.

== Postdeployment steps

Configure a https://help.salesforce.com/s/articleView?id=sf.video_call_create_a_named_credential.htm&type=5[{partner-company-short-name} Named Credential^] so that {partner-product-short-name} can invoke AWS services.

To use AWS Identity and Access Management (IAM) to retrieve the user's access key and secret that's generated by this Partner Solution, do the following steps:

. Log in to your AWS account. This account must have sufficient privileges to create an access key for the service account. For more information, refer to https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateAccessKey.html[CreateAccessKey^].
. In the AWS Management Console, choose *Services > Identity Access Management (IAM)*.
. Choose *Users*.
. Choose the user specified in the AWS CloudFormation template definition.
. Choose the *Security Credentials* tab.
. Under the *Access Key* section, choose *Create access key*. This action creates an access key and allows you to copy or download the contents.

The access key ID and secret access key is used to configure a {partner-company-short-name} Named Credential.

[#upgrade]
== Upgrade an existing deployment of Virtual Calls

If upgrading an existing deployment of {partner-product-short-name}, perform the following steps:

. Do the following steps to download the latest template file from GitHub:
.. Navigate to the https://fwd.aws/VVvWr?[Partner Solution landing page].
.. Choose *View the source code for this Partner Solution* to open the GitHub repository.
.. Open the *template* folder to access the latest CloudFormation template. 
.. Download the template. 
. In the AWS Management Console, choose *Services > CloudFormation*.
. Choose the existing Virtual Care stack. 
. Choose *Update* to open the *Update stack* page.
. Choose *Replace current template*, and upload the template file. Choose *Next*.
. On the *Specify stack details* page, review the stack settings and update the control Region (for example, us-east-1) and messaging Region (for example, us-east-1). Choose *Next*.
. On the *Configure stack options* page, review the changes and choose *Next*.
. On the *Review* page, review and confirm template settings. Under *Capabilities*, select all of the check boxes to acknowledge that the template creates AWS Identity and Access Management (IAM) resources that might require the ability to automatically expand macros.
. Choose *Submit*. The stack takes about 5 minutes to update.
. Monitor the stack's status, and when the status is *UPDATE_COMPLETE*, the {partner-product-name} deployment is ready.  
